language: ruby
rvm:
- 2.3.3

before_script:
  - gem install jekyll
  - bundle install
  - bundle exec jekyll build

script: bundle exec htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false