language: ruby
rvm:
- 2.0.0

install:
  - gem uninstall bundler
  - gem install bundler --version '1.14.5'
  - bundle install

script: bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false