language: ruby
rvm:
- 2.3.3

before_install:
  - gem update --system
  - gem --version

before_script:
  - gem install jekyll
  - bundle install

script: bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false