---
title: dariustehrani.io
email: web@dariustehrani.io

description: Darius Tehrani - IT Strategie & Cloud Architektur Beratung
baseurl: ''
url: http://dariustehrani.io
github_username: datadarius
xing_username: Darius_Tehrani
linkedin_username: dtehrani
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
timezone: Europe/Berlin
