---
title: dariustehrani.io
email: web@dariustehrani.io
description: Darius Tehrani - IT Strategie & Cloud Architektur
keywords: 'Cloud Architektur, IT Strategie, Digitale Kollaboration, Agile, DevOps, IT Konzeption, IT Management, Digital Transformation, Köln, Cologne, Kubernetes, Docker'
baseurl: ''
url: http://dariustehrani.io
github_username: datadarius
xing_username: Darius_Tehrani
linkedin_username: dtehrani
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
timezone: Europe/Berlin
google_analytics: UA-91039215-1
